// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

// Injectors from wire.go:

func CreateApp() *Application {
	dbGateway := NewDbGateway()
	application := NewApplication(dbGateway)
	return application
}
